version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: facultyForm-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - mern-network
  backend:
    build: ./backend/facultyFormCloneBackend
    container_name: facultyForm-backend
    restart: always
    ports: 
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - mern-network
  frontend:
    build: ./frontend/facultyFormCloneFrontend
    container_name: factultyForm-UI
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network
networks:
  mern-network:
    driver: bridge
volumes:
  data: